language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source
  - composer require satooshi/php-coveralls:dev-master --prefer-source

script:
  - phpunit -v --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
